services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=john.ellingsen@visinnovasjon.no
      - PGADMIN_DEFAULT_PASSWORD=VIS2024
    volumes:
      - ./pgAdmin:/var/lib/pgadmin
